# Exploratory Data Analysis

Understanding the dataset to explore how the data is present in the database and if there is a need
of creating some aggregated tables that can help with 

* Vender selection for profitability
* Product Pricing Optimization

In [1]:
import sqlite3
import pandas as pd
conn=sqlite3.connect('inventory.db')

In [3]:
tables=pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",conn)
tables

                   name
0                    df
1       begin_inventory
2         end_inventory
3             purchases
4       purchase_prices
5                 sales
6        vendor_invoice
7   vendor_sales_summar
8  vendor_sales_summary

In [4]:
for table in tables['name']:
    print('-'*50,f'{table}','-'*50)
    print("count of record",pd.read_sql(f"select count(*) as count from {table}",conn)['count'].values[0])
    display(pd.read_sql(f'select *from {table} limit 4',conn))

-------------------------------------------------- df --------------------------------------------------
count of record 8427

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,95004,1536214.68,19071.0,419402.29,40992.36,35041.49,257032.07,-1116812.39,-266.286670,0.200739,0.273010
1,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,57735,1516698.45,9080.0,326789.20,61614.88,16683.12,68601.68,-1189909.25,-364.121351,0.157270,0.215461
2,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,59222,1373358.18,8802.0,263533.98,49183.57,16172.33,144929.24,-1109824.20,-421.131347,0.148627,0.191890
3,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,69475,1267224.00,10243.0,264494.57,45628.33,18819.83,123780.22,-1002729.43,-379.111537,0.147434,0.208720

-------------------------------------------------- begin_inventory --------------------------------------------------
count of record 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
count of record 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31

-------------------------------------------------- purchases --------------------------------------------------
count of record 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1

-------------------------------------------------- purchase_prices --------------------------------------------------
count of record 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP

-------------------------------------------------- sales --------------------------------------------------
count of record 10000000

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
count of record 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None

-------------------------------------------------- vendor_sales_summar --------------------------------------------------
count of record 10692

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,107436.0,3881420.64,549794.09,197400.84,68601.68,70169.04,1.807818,0.740529,1.018411
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,124473.0,3767851.23,459750.89,228706.96,144929.24,-36189.99,-0.960494,0.758806,0.990486
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,149367.0,3643388.83,378570.51,274449.16,123780.22,225085.15,6.177906,0.797019,1.065847
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,140201.0,3200219.99,343315.16,257608.11,257032.07,-60977.95,-1.905430,0.695159,0.981302

-------------------------------------------------- vendor_sales_summary --------------------------------------------------
count of record 10692

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,107436.0,3881420.64,549794.09,197400.84,68601.68,70169.04,1.807818,0.740529,1.018411
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,124473.0,3767851.23,459750.89,228706.96,144929.24,-36189.99,-0.960494,0.758806,0.990486
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,149367.0,3643388.83,378570.51,274449.16,123780.22,225085.15,6.177906,0.797019,1.065847
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,140201.0,3200219.99,343315.16,257608.11,257032.07,-60977.95,-1.905430,0.695159,0.981302

In [4]:
purchase_prices=pd.read_sql_query("select * from purchase_prices where VendorNumber = 4466", conn)
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [5]:
purchases=pd.read_sql_query("select * from purchases where VendorNumber = 4466", conn)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [6]:
 sales=pd.read_sql_query("""select * from  sales where VendorNo=4466 """, conn)
 sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
1,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-12,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-15,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
4,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7433,63_SWORDBREAK_5215,63,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-10-20,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
7434,63_SWORDBREAK_5255,63,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-10-02,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
7435,63_SWORDBREAK_5255,63,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-10-05,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
7436,63_SWORDBREAK_5255,63,5255,TGI Fridays Ultimte Mudslide,1.75L,2,25.98,12.99,2024-10-07,1750.0,1,3.67,4466,AMERICAN VINTAGE BEVERAGE
7437,63_SWORDBREAK_5255,63,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-10-29,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE

In [7]:
vendor_invoice =pd.read_sql_query("select * from vendor_invoice  where VendorNumber = 4466", conn)
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-19,8207,2023-12-27,2024-02-26,335,3142.33,16.97,None
2,4466,AMERICAN VINTAGE BEVERAGE,2024-01-18,8307,2024-01-03,2024-02-18,41,383.35,1.99,None
3,4466,AMERICAN VINTAGE BEVERAGE,2024-01-27,8469,2024-01-14,2024-03-11,72,673.20,3.30,None
4,4466,AMERICAN VINTAGE BEVERAGE,2024-02-04,8532,2024-01-19,2024-03-15,79,740.21,3.48,None
5,4466,AMERICAN VINTAGE BEVERAGE,2024-02-09,8604,2024-01-24,2024-03-15,347,3261.37,17.61,None
6,4466,AMERICAN VINTAGE BEVERAGE,2024-02-17,8793,2024-02-05,2024-04-02,72,675.36,3.17,None
7,4466,AMERICAN VINTAGE BEVERAGE,2024-03-01,8892,2024-02-12,2024-03-28,117,1096.05,5.15,None
8,4466,AMERICAN VINTAGE BEVERAGE,2024-03-07,8995,2024-02-19,2024-04-02,129,1209.27,5.44,None
9,4466,AMERICAN VINTAGE BEVERAGE,2024-03-12,9033,2024-02-22,2024-04-16,147,1377.87,6.61,None
10,4466,AMERICAN VINTAGE BEVERAGE,2024-03-16,9180,2024-03-03,2024-04-19,211,1979.33,9.50,None
11,4466,AMERICAN VINTAGE BEVERAGE,2024-03-23,9244,2024-03-08,2024-04-21,161,1510.69,6.95,None
12,4466,AMERICAN VINTAGE BEVERAGE,2024-03-31,9371,2024-03-17,2024-05-13,176,1649.20,8.91,None
13,4466,AMERICAN VINTAGE BEVERAGE,2024-04-09,9491,2024-03-24,2024-05-08,215,2016.43,10.08,None
14,4466,AMERICAN VINTAGE BEVERAGE,2024-04-17,9583,2024-03-31,2024-05-12,110,1035.10,5.69,None
15,4466,AMERICAN VINTAGE BEVERAGE,2024-04-20,9639,2024-04-04,2024-06-04,515,5323.01,25.02,None
16,4466,AMERICAN VINTAGE BEVERAGE,2024-04-29,9800,2024-04-15,2024-06-07,275,2775.01,13.60,None
17,4466,AMERICAN VINTAGE BEVERAGE,2024-05-09,9886,2024-04-21,2024-06-12,312,3050.86,13.73,None
18,4466,AMERICAN VINTAGE BEVERAGE,2024-05-14,9999,2024-04-29,2024-06-26,310,3117.82,14.97,None
19,4466,AMERICAN VINTAGE BEVERAGE,2024-05-16,10095,2024-05-06,2024-06-27,215,2123.01,11.46,None
20,4466,AMERICAN VINTAGE BEVERAGE,2024-05-28,10169,2024-05-11,2024-07-04,327,3298.55,15.83,None
21,4466,AMERICAN VINTAGE BEVERAGE,2024-06-04,10257,2024-05-17,2024-07-08,376,3708.18,20.39,None
22,4466,AMERICAN VINTAGE BEVERAGE,2024-06-12,10346,2024-05-23,2024-07-20,640,6458.38,29.71,None
23,4466,AMERICAN VINTAGE BEVERAGE,2024-06-17,10445,2024-05-30,2024-07-19,288,2937.56,15.86,None
24,4466,AMERICAN VINTAGE BEVERAGE,2024-06-22,10600,2024-06-09,2024-08-01,308,3213.28,17.03,None
25,4466,AMERICAN VINTAGE BEVERAGE,2024-06-29,10695,2024-06-16,2024-08-12,143,1585.75,8.09,None
26,4466,AMERICAN VINTAGE BEVERAGE,2024-07-09,10777,2024-06-22,2024-08-15,18,179.88,0.99,None
27,4466,AMERICAN VINTAGE BEVERAGE,2024-07-08,10836,2024-06-25,2024-08-14,8,85.96,0.43,None
28,4466,AMERICAN VINTAGE BEVERAGE,2024-07-11,10969,2024-06-29,2024-08-18,94,993.12,5.06,None
29,4466,AMERICAN VINTAGE BEVERAGE,2024-07-19,11085,2024-07-06,2024-09-04,601,5883.09,31.18,None
30,4466,AMERICAN VINTAGE BEVERAGE,2024-07-26,11187,2024-07-14,2024-08-26,1535,15406.69,77.03,None
31,4466,AMERICAN VINTAGE BEVERAGE,2024-08-03,11244,2024-07-18,2024-09-04,266,2888.22,15.31,None
32,4466,AMERICAN VINTAGE BEVERAGE,2024-08-11,11362,2024-07-26,2024-09-24,206,2171.64,11.08,None
33,4466,AMERICAN VINTAGE BEVERAGE,2024-08-18,11489,2024-08-04,2024-09-16,768,7292.98,37.92,None
34,4466,AMERICAN VINTAGE BEVERAGE,2024-08-24,11540,2024-08-08,2024-10-02,1207,12242.43,64.88,None
35,4466,AMERICAN VINTAGE BEVERAGE,2024-09-02,11716,2024-08-19,2024-09-29,433,4334.43,20.37,None
36,4466,AMERICAN VINTAGE BEVERAGE,2024-09-12,11771,2024-08-23,2024-10-11,370,3640.18,18.20,None
37,4466,AMERICAN VINTAGE BEVERAGE,2024-09-20,11901,2024-09-01,2024-10-30,358,3626.74,16.32,None
38,4466,AMERICAN VINTAGE BEVERAGE,2024-09-25,11993,2024-09-07,2024-10-23,233,2264.85,12.23,None
39,4466,AMERICAN VINTAGE BEVERAGE,2024-10-01,12125,2024-09-16,2024-11-07,284,2813.46,15.47,None
40,4466,AMERICAN VINTAGE BEVERAGE,2024-10-08,12235,2024-09-23,2024-11-20,258,2592.08,11.92,None
41,4466,AMERICAN VINTAGE BEVERAGE,2024-10-09,12253,2024-09-23,2024-11-14,1,11.19,0.05,None
42,4466,AMERICAN VINTAGE BEVERAGE,2024-10-12,12321,2024-09-26,2024-11-19,172,1685.98,7.59,None
43,4466,AMERICAN VINTAGE BEVERAGE,2024-10-20,12466,2024-10-05,2024-11-26,280,2798.60,14.55,None
44,4466,AMERICAN VINTAGE BEVERAGE,2024-10-27,12515,2024-10-09,2024-11-30,178,1763.28,8.64,None
45,4466,AMERICAN VINTAGE BEVERAGE,2024-11-07,12702,2024-10-21,2024-12-11,183,1812.77,8.70,None
46,4466,AMERICAN VINTAGE BEVERAGE,2024-11-12,12752,2024-10-25,2024-12-11,216,2156.16,10.57,None
47,4466,AMERICAN VINTAGE BEVERAGE,2024-11-20,12828,2024-10-30,2024-12-18,262,2597.36,12.99,None
48,4466,AMERICAN VINTAGE BEVERAGE,2024-11-27,12929,2024-11-06,2025-01-04,270,2622.32,12.85,None
49,4466,AMERICAN VINTAGE BEVERAGE,2024-11-28,13092,2024-11-16,2024-12-30,209,2036.17,11.20,None
50,4466,AMERICAN VINTAGE BEVERAGE,2024-12-06,13134,2024-11-20,2025-01-18,305,3018.89,15.70,None
51,4466,AMERICAN VINTAGE BEVERAGE,2024-12-16,13254,2024-11-28,2025-01-13,262,2530.36,11.39,None
52,4466,AMERICAN VINTAGE BEVERAGE,2024-12-26,13432,2024-12-09,2025-01-27,231,2263.43,11.32,None
53,4466,AMERICAN VINTAGE BEVERAGE,2024-12-30,13483,2024-12-13,2025-02-11,221,2178.27,11.33,None
54,4466,AMERICAN VINTAGE BEVERAGE,2025-01-09,13627,2024-12-22,2025-02-05,413,3985.03,19.53,None

In [8]:
purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [9]:
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [10]:
vendor_invoice['PONumber'].nunique()

55

In [11]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [12]:
vendor_invoice.shape

(55, 10)

In [13]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [14]:
purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [15]:
sales.groupby("Brand")[["SalesDollars","SalesPrice","SalesQuantity"]].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
3140       41918.73    23420.97           3227
5215       48881.37    33059.55           3763
5255       61910.34    40139.10           4766

* The Purchase table cotains actual purchase data,including the data of purchase, product(brand) purchases by vendors the amount paid (in dollore) and the quantity purchased
* The purchase price columns is divided from the purchase_price table, which provide product - wise actual and purchase price .
  the combination of vendor and brand is unique in this table
* The vendor_invoice tables aggregates data from the purchase tables, summarizing quantity and dollar, along with an addition columns
  for freight this tables maintain uniqueness based on vendor and PO number
* The sales table capture actual sales datailing the purchaseed by vendors, the quantitty sold , the selling price
  and the revenue erned.

As the data that we need for analysis is distributed tables, we need to create a summary table containing

* purchase transactionas made by vendor
* sales transaction data
* frieght costs for each vendor
* actual product price from vendors

In [16]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [17]:
freight_summary=pd.read_sql_query("""select VendorNumber, SUM(freight) as FreightCost From vendor_invoice Group BY VendorNumber""",conn)

In [18]:
freight_summary

     VendorNumber  FreightCost
0               2        27.08
1              54         0.48
2              60       367.52
3             105        62.39
4             200         6.19
..            ...          ...
121         98450       856.02
122         99166       130.09
123        172662       178.34
124        173357       202.50
125        201359         0.09

[126 rows x 2 columns]

In [19]:
pd.read_sql_query("""select
p.VendorNumber,
p.VendorName, 
p.Brand,
pp.volume,
pp.Price as ActualPrice,
p.Purchaseprice,
SUM(p.Quantity) as TotalPurchaseQuantity,
SUM(p.Dollars) as TotalPurchaseDollars 
from purchases p
JOIN purchase_prices pp
ON p.Brand = pp.Brand
where p.purchaseprice>0
GROUP BY p.VendorNumber, p.VendorName, p.Brand
ORDER BY TotalPurchaseDollars""", conn)

,VendorNumber,VendorName,Brand,Volume,ActualPrice,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,7245,PROXIMO SPIRITS INC.,3065,50,0.99,0.71,1,0.71
1,3960,DIAGEO NORTH AMERICA INC,6127,200,1.99,1.47,1,1.47
2,3924,HEAVEN HILL DISTILLERIES,9123,50,0.99,0.74,2,1.48
3,8004,SAZERAC CO INC,5683,50,0.49,0.39,6,2.34
4,9815,WINE GROUP INC,8527,750,4.99,1.32,2,2.64
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,1750,29.99,21.89,138109,3023206.01
10688,3960,DIAGEO NORTH AMERICA INC,4261,1750,22.99,16.17,201682,3261197.94
10689,17035,PERNOD RICARD USA,8068,1750,24.99,18.24,187407,3418303.68
10690,4425,MARTIGNETTI COMPANIES,3405,1750,28.99,23.19,164038,3804041.22
10691,1128,BROWN-FORMAN CORP,1233,1750,36.99,26.27,145080,3811251.60

In [20]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [21]:
pd.read_sql_query("""select
VendorNo,
Brand,
SUM(SalesDollars) as TotalSalesDollars,
SUM(SalesPrice) as TotalSalesPrice,
SUM(SalesQuantity) as TotalSalesQuantity,
SUM(ExciseTax) as TotalExciseTax
FROM sales

Group by VendorNo, Brand
ORDER BY TotalSalesDollars""",conn)

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,8004,5287,0.98,0.98,2,0.10
1,9206,2773,0.99,0.99,1,0.05
2,3252,3933,1.98,0.99,2,0.10
3,10050,3623,1.98,1.98,2,0.10
4,660,2134,2.49,2.49,1,0.39
...,...,...,...,...,...,...
10808,3960,4261,3200219.99,343315.16,140201,257608.11
10809,3960,3545,3209878.83,443700.00,102317,187995.79
10810,17035,8068,3643388.83,378570.51,149367,274449.16
10811,4425,3405,3767851.23,459750.89,124473,228706.96
10812,1128,1233,3881420.64,549794.09,107436,197400.84

In [22]:
vendor_sales_summary = pd.read_sql_query("""WITH FreightSummary AS (
    SELECT
        VendorNumber,
        SUM(Freight) AS FreightCost
    FROM vendor_invoice
    GROUP BY VendorNumber
),

PurchaseSummary AS (
    SELECT
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price AS ActualPrice,
        pp.Volume,
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.Dollars) AS TotalPurchaseDollars
    FROM purchases p
    JOIN purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY 
        p.VendorNumber, 
        p.VendorName, 
        p.Brand,
        p.Description,
        p.PurchasePrice, 
        pp.Price,
        pp.Volume
),

SalesSummary AS (
    SELECT 
        VendorNo,
        Brand,
        SUM(SalesQuantity) AS TotalSalesQuantity,
        SUM(SalesDollars) AS TotalSalesDollars,
        SUM(SalesPrice) AS TotalSalesPrice,
        SUM(ExciseTax) AS TotalExciseTax
    FROM sales ss
    GROUP BY VendorNo, Brand
)

SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalExciseTax,
    fs.FreightCost

FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
ON ps.VendorNumber=ss.VendorNo
AND ps.Brand=ss.Brand
LEFT JOIN FreightSummary fs
ON ps.VendorNumber=fs.VendorNumber
ORDER BY ps.TotalPurchaseDollars DESC
""", conn)

In [23]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,145080,3811251.60,107436.0,3881420.64,549794.09,197400.84,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,164038,3804041.22,124473.0,3767851.23,459750.89,228706.96,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,187407,3418303.68,149367.0,3643388.83,378570.51,274449.16,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,201682,3261197.94,140201.0,3200219.99,343315.16,257608.11,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,138109,3023206.01,102317.0,3209878.83,443700.00,187995.79,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750,2,2.64,5.0,15.95,10.96,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50,6,2.34,134.0,65.66,1.47,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50,2,1.48,NaN,NaN,NaN,NaN,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200,1,1.47,57.0,113.43,55.72,11.97,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50,1,0.71,86.0,85.14,33.66,4.46,38994.78

This query generates a vendor - wise sales and purchases summary , which is valuable for:
Performance Optimization:

# performance optimization:
* The query involves heavy joins and aggregations on large datasets like sales and purchases:
* Storing the pre - aggregated results avoids repeated expensive computations
* Help in analyzing sales, purchases and pricing for different vendors and brands
* Future Benefits of storing this data for faster Dashboarding & reportting.
* Instead of running expensive queries each time , dashboards can fetch data quickly from vendor_sales_summary

In [24]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
ActualPrice              float64
Volume                    object
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [25]:
vendor_sales_summary.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
PurchasePrice              0
ActualPrice                0
Volume                     0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
TotalSalesQuantity       631
TotalSalesDollars        631
TotalSalesPrice          631
TotalExciseTax           631
FreightCost                0
dtype: int64

In [26]:
df=vendor_sales_summary

In [27]:
df["VendorName"].unique()

array(['BROWN-FORMAN CORP          ', 'MARTIGNETTI COMPANIES',
       'PERNOD RICARD USA          ', 'DIAGEO NORTH AMERICA INC   ',
       'BACARDI USA INC            ', 'JIM BEAM BRANDS COMPANY    ',
       'MAJESTIC FINE WINES        ', 'ULTRA BEVERAGE COMPANY LLP ',
       'STOLI GROUP,(USA) LLC      ', 'PROXIMO SPIRITS INC.       ',
       'MOET HENNESSY USA INC      ', 'CAMPARI AMERICA            ',
       'SAZERAC CO INC             ', 'CONSTELLATION BRANDS INC   ',
       'M S WALKER INC             ', 'SAZERAC NORTH AMERICA INC. ',
       'PALM BAY INTERNATIONAL INC ', 'REMY COINTREAU USA INC     ',
       'SIDNEY FRANK IMPORTING CO  ', 'E & J GALLO WINERY         ',
       'WILLIAM GRANT & SONS INC   ', 'HEAVEN HILL DISTILLERIES   ',
       'DISARONNO INTERNATIONAL LLC', 'EDRINGTON AMERICAS         ',
       'CASTLE BRANDS CORP.        ', 'SOUTHERN WINE & SPIRITS NE ',
       'STE MICHELLE WINE ESTATES  ', 'TRINCHERO FAMILY ESTATES   ',
       'MHW LTD                    ', 'WINE GROUP INC             ',
       'PERFECTA WINES             ', 'LUXCO INC                  ',
       'TREASURY WINE ESTATES      ', 'DIAGEO CHATEAU ESTATE WINES',
       'SHAW ROSS INT L IMP LTD    ', 'PINE STATE TRADING CO      ',
       'PHILLIPS PRODUCTS CO.      ', 'CALEDONIA SPIRITS INC      ',
       'STATE WINE & SPIRITS   ', 'KOBRAND CORPORATION        ',
       'BANFI PRODUCTS CORP        ', 'VINEYARD BRANDS INC        ',
       'DELICATO VINEYARDS INC     ', 'FABRIZIA SPIRITS LLC       ',
       'DUGGANS DISTILLED PRODUCTS ', 'Serralles Usa LLC          ',
       'SEA HAGG DISTILLERY LLC    ', 'OLE SMOKY DISTILLERY LLC   ',
       'VRANKEN AMERICA            ', 'KLIN SPIRITS LLC           ',
       'LAIRD & CO                 ', 'ADAMBA IMPORTS INTL INC    ',
       'LATITUDE BEVERAGE COMPANY  ', 'FREDERICK WILDMAN & SONS   ',
       'MCCORMICK DISTILLING CO    ', 'CHARLES JACQUIN ET CIE INC ',
       'WESTERN SPIRITS BEVERAGE CO', 'MARSALLE COMPANY           ',
       'AMERICAN VINTAGE BEVERAGE  ', 'MANGO BOTTLING INC         ',
       'SWEET BABY VINEYARD        ', 'NICHE W & S                ',
       'LABELLE VYDS AND WINERY    ', 'FLAG HILL WINERY & VINEYARD',
       'SMOKY QUARTZ DISTILLERY LLC', 'PREMIUM PORT WINES, INC.   ',
       'Russian Standard Vodka     ', 'Dunn Wine Brokers          ',
       'WEIN BAUER INC             ', 'BULLY BOY DISTILLERS       ',
       'ATLANTIC IMPORTING COMPANY ', 'PREMIER DISTRIBUTORS       ',
       'VINILANDIA USA             ', 'PARK STREET IMPORTS LLC    ',
       'TAKARA SAKE USA INC        ', 'SEA BREEZE CELLARS LLC     ',
       'STARK BREWING COMPANY      ', 'TY KU LLC                  ',
       'PSP WINES ', 'TAMWORTH DISTILLING        ',
       'ZORVINO VINEYARDS          ', 'SOUTHERN GLAZERS W&S OF NE ',
       'HOOD RIVER DISTILLERS, Inc.', 'CRUSH WINES                ',
       'POVERTY LANE ORCHARDS      ', 'DJINN SPIRITS LLC          ',
       'MOONLIGHT MEADERY          ', 'TALL SHIP DISTILLERY LLC   ',
       'FORTUNE WINE BROKERS LLC   ', 'BLACK COVE BEVERAGES       ',
       'VINEXTRA INC               ', 'SURVILLE ENTERPRISES CORP  ',
       'JEWELL TOWNE VINEYARDS     ', 'SWEETWATER FARM         ',
       'MARTIGNETTI COMPANIES ', 'ALTAMAR BRANDS LLC         ',
       'CANDIA VINEYARDS           ', 'INCREDIBREW INC            ',
       'ALISA CARR BEVERAGES           ', 'STELLAR IMPORTING CO LLC   ',
       'FULCHINO VINEYARD INC      ',
       'IRA GOLDMAN AND WILLIAMS, LLP          ',
       'Circa Wines                ', 'VINEDREA WINES LLC         ',
       'BLACK PRINCE DISTILLERY INC', 'VINEYARD BRANDS LLC        ',
       'THE IMPORTED GRAPE LLC     ', 'WALPOLE MTN VIEW WINERY    ',
       'GILMANTON WINERY & VINEYARD', 'HAUNTING WHISPER VYDS      ',
       'STAR INDUSTRIES INC.       ', 'LOYAL DOG WINERY           ',
       'R.P.IMPORTS INC            ', 'THE PIERPONT GROUP LLC     ',
       'APPOLO VINEYARDS LLC       ', 'BLACK ROCK SPIRITS LLC     ',
       'CENTEUR IMPORTS LLC        ', 'HIGHLAND WINE MERCHANTS LLC',
       'AMERICAN SPIRITS EXCHANGE  ', 'UNCORKED       ',
       'BRONCO WINE COMPANY        ', 'MILTONS DISTRIBUTING CO    ',
       'TRUETT HURST               ', 'LAUREATE IMPORTS CO        ',
       'FANTASY FINE WINES CORP    ', 'AAPER ALCOHOL & CHEMICAL CO',
       'SILVER MOUNTAIN CIDERS     ', 'CAPSTONE INTERNATIONAL     ',
       'FLAVOR ESSENCE INC         '], dtype=object)

In [28]:
df['Volume']=df['Volume'].astype('float64')

In [29]:
df.fillna(0,inplace=True)

In [30]:
df.isnull().sum()

VendorNumber             0
VendorName               0
Brand                    0
Description              0
PurchasePrice            0
ActualPrice              0
Volume                   0
TotalPurchaseQuantity    0
TotalPurchaseDollars     0
TotalSalesQuantity       0
TotalSalesDollars        0
TotalSalesPrice          0
TotalExciseTax           0
FreightCost              0
dtype: int64

In [31]:
df["VendorName"]=df["VendorName"].str.strip()

In [32]:
df['GrossProfit']=df["TotalSalesDollars"]-df["TotalPurchaseDollars"]

In [33]:
df

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,107436.0,3881420.64,549794.09,197400.84,68601.68,70169.04
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,124473.0,3767851.23,459750.89,228706.96,144929.24,-36189.99
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,149367.0,3643388.83,378570.51,274449.16,123780.22,225085.15
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,140201.0,3200219.99,343315.16,257608.11,257032.07,-60977.95
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,102317.0,3209878.83,443700.00,187995.79,257032.07,186672.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750.0,2,2.64,5.0,15.95,10.96,0.55,27100.41,13.31
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50.0,6,2.34,134.0,65.66,1.47,7.04,50293.62,63.32
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50.0,2,1.48,0.0,0.00,0.00,0.00,14069.87,-1.48
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200.0,1,1.47,57.0,113.43,55.72,11.97,257032.07,111.96
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50.0,1,0.71,86.0,85.14,33.66,4.46,38994.78,84.43

In [34]:
df["ProfitMargin"]=df["GrossProfit"]/df["TotalSalesDollars"]*100

In [35]:
df["ProfitMargin"]

0         1.807818
1        -0.960494
2         6.177906
3        -1.905430
4         5.815572
           ...
10687    83.448276
10688    96.436186
10689         -inf
10690    98.704047
10691    99.166079
Name: ProfitMargin, Length: 10692, dtype: float64

In [36]:
df["StockTurnover"]=df["TotalSalesQuantity"]/df["TotalPurchaseQuantity"]

In [37]:
df["SalestoPurchaseRatio"]=df["TotalSalesDollars"]/df["TotalPurchaseDollars"]

In [38]:
df=vendor_sales_summary

In [39]:
cursor=conn.cursor()

In [40]:
df.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'Description', 'PurchasePrice',
       'ActualPrice', 'Volume', 'TotalPurchaseQuantity',
       'TotalPurchaseDollars', 'TotalSalesQuantity', 'TotalSalesDollars',
       'TotalSalesPrice', 'TotalExciseTax', 'FreightCost', 'GrossProfit',
       'ProfitMargin', 'StockTurnover', 'SalestoPurchaseRatio'],
      dtype='object')

In [41]:
cursor.execute("""create table if not exists vendor_sales_summary (
VendorNumber INT,
VendorName Varchar(100),
Brand int,
Description varchar(100),
PurchasePrice decimal(10,2),
Volume,
TotalPurchaseQuantity INT,
TotalPurchaseDollars decimal(15,2),
TotalSalesQuantity INT,
TotalSalesDollars decimal(15,2),
TotalSalesPrice decimal(15,2),
TotalExciseTax decimal(15,2),
FreightCost decimal(15,2),
GrossProfit decimal(15,2),
ProfitMargin decimal(15,2),
StockTurnover decimal(15,2),
SalestoPurchaseRatio decimal(15,2),
Primary Key (VendorNumber, Brand)
);""")

In [42]:
pd.read_sql_query("""select * from  vendor_sales_summary""",conn)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,28570.0,1028234.30,180489.85,52493.23,68601.68,-2783017.30,-270.659839,0.196926,0.269789
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,26217.0,791848.43,146709.75,48170.03,144929.24,-3012192.79,-380.400172,0.159823,0.208160
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,34629.0,873900.71,128795.05,63626.42,123780.22,-2544402.97,-291.154698,0.184780,0.255653
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,55658.0,1239556.42,118462.86,102267.41,257032.07,-2021641.52,-163.093949,0.275969,0.380092
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,29744.0,912078.56,143162.65,54650.80,257032.07,-2111127.45,-231.463335,0.215366,0.301692
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750.0,2,2.64,3.0,5.97,5.97,0.33,27100.41,3.33,55.778894,1.500000,2.261364
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50.0,6,2.34,128.0,62.72,0.98,6.72,50293.62,60.38,96.269133,21.333333,26.803419
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50.0,2,1.48,0.0,0.00,0.00,0.00,14069.87,-1.48,-inf,0.000000,0.000000
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200.0,1,1.47,8.0,15.92,9.95,1.68,257032.07,14.45,90.766332,8.000000,10.829932
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50.0,1,0.71,85.0,84.15,32.67,4.41,38994.78,83.44,99.156269,85.000000,118.521127

In [43]:
vendor_sales_summary.to_sql('vendor_sales_summar',conn, if_exists="replace", index=False)

10692

In [44]:
import sqlite3
import pandas as pd
import logging
from ingestion_db import ingest_db

logging.basicConfig(
    filename="logs/get_vendor_summary.log",
    level=logging.DEBUG,
    format="%(asctime)s-%(levelname)s-%(message)s",
    filemode="a"
)

def create_vendor_summary(conn):
    """this funtion will merge the different tables to get the overall vendor summary and adding new columns in the resultant data"""
    vendor_sales_summary = pd.read_sql_query("""WITH FreightSummary AS (
    SELECT
        VendorNumber,
        SUM(Freight) AS FreightCost
    FROM vendor_invoice
    GROUP BY VendorNumber
),

PurchaseSummary AS (
    SELECT
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price AS ActualPrice,
        pp.Volume,
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.Dollars) AS TotalPurchaseDollars
    FROM purchases p
    JOIN purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY 
        p.VendorNumber, 
        p.VendorName, 
        p.Brand,
        p.Description,
        p.PurchasePrice, 
        pp.Price,
        pp.Volume
),

SalesSummary AS (
    SELECT 
        VendorNo,
        Brand,
        SUM(SalesQuantity) AS TotalSalesQuantity,
        SUM(SalesDollars) AS TotalSalesDollars,
        SUM(SalesPrice) AS TotalSalesPrice,
        SUM(ExciseTax) AS TotalExciseTax
    FROM sales ss
    GROUP BY VendorNo, Brand
)

SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalExciseTax,
    fs.FreightCost
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
ON ps.VendorNumber=ss.VendorNo
AND ps.Brand=ss.Brand
LEFT JOIN FreightSummary fs
ON ps.VendorNumber=fs.VendorNumber
ORDER BY ps.TotalPurchaseDollars DESC
""", conn)
    return vendor_sales_summary  

def clean_data(df):
    """This funtion will clean data"""
    #changing the data type into float
    df["Volume"]=df["Volume"].astype("float")
    
    # filling mssing values with 0
    df.fillna(0,inplace=True)

    # Removing spaces from categorial columns
    df['VendorNumber']=df['VendorNumber'].astype(str).str.strip()
    df['Description'] = df['Description'].astype(str).str.strip()


    
    # creating new columns for better analysis

    df['GrossProfit']=df["TotalSalesDollars"]-df["TotalPurchaseDollars"]
    df["ProfitMargin"]=df["GrossProfit"]/df["TotalSalesDollars"]*100
    df["StockTurnover"]=df["TotalSalesQuantity"]/df["TotalPurchaseQuantity"]
    df["SalestoPurchaseRatio"]=df["TotalSalesDollars"]/df["TotalPurchaseDollars"]
    
    return df

if __name__=='__main__':
    # creating database connection 
    conn = sqlite3.connect('inventory.db')

    logging.info('Creating Vendor Summary Table....')
    summary_df=create_vendor_summary(conn)
    logging.info(summary_df.head())

    logging.info("cleaning Data...")
    clean_df=clean_data(summary_df)
    logging.info(clean_df.head())

    logging.info('Ingesting data...')
    ingest_db(clean_df,'vendor_sales_summary',conn)
    logging.info('Completed')